apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern
  labels:
    app: mern
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern
  template:
    metadata:
      labels:
        app: mern
    spec:
      containers:
        - name: mern_backend
          image: durlavparajuli/mern_backend:latest
          ports:
            - containerPort: 5000
        - name: mern_frontend
          image: durlavparajuli/mern_frontend:latest
          ports:
            - containerPort: 5173
