apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend-deployment
  labels:
    app: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-backend
          image: durlavparajuli/mern_backend:v1
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
spec:
  type: NodePort
  selector:
    app: mern-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
